#!/usr/bin/env bun
import { Glob } from "bun"
import path from "path"
import fs from "fs"
import { fileURLToPath } from "url"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..")
const skillsRoot = path.join(root, ".fuckcode", "skills")
const outFile = path.join(root, "packages", "opencode", "src", "skill", "embedded.gen.ts")

const files = (await Array.fromAsync(new Glob("**/SKILL.md").scan({ cwd: skillsRoot, onlyFiles: true }))).toSorted()

const entries: Record<string, string> = {}
for (const file of files) {
  entries[file] = await Bun.file(path.join(skillsRoot, file)).text()
}

const header = `// Generated by packages/opencode/script/generate-embedded-skills.ts. Do not edit.
// Regenerate with: bun run packages/opencode/script/generate-embedded-skills.ts
`

await Bun.write(outFile, `${header}export const EMBEDDED_SKILLS: Record<string, string> = ${JSON.stringify(entries, null, 2)}\n`)
console.log(`embedded ${files.length} skills into ${path.relative(root, outFile)}`)
